Update objetivo-0.md
JJ/IV-21-22 pull request #55
Opened 2021-09-21 17:17 UTC by juanfran00

# Entrega del hito/objetivo del proyecto de Infraestructura virtual

## Primero y mas importante

* [ ] NOCERRAR: No voy a cerrar ningún PR pase lo que pase.

## Lista de comprobación para hitos

* [ ] GUION: He leído el guión del hito
* [ ] PRE: Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)

2021-09-21 18:46 UTC, JJ requested changes
Por favor, cambia la versión que es lo que os he dicho en las instrucciones, que para eso está esa columna.

2021-09-21 18:59 UTC, juanfran00 commented
Perdón profesor por haber enviado tantos PR y no cambiar la versión, ya he cambiado la versión el los fallos me dice que he cambiado la línea de LuisS20 cuando solo he cambiado mi línea no entiendo.

2021-09-22 05:16 UTC, JJ commented
> Perdón profesor por haber enviado tantos PR y no cambiar la versión, ya he cambiado la versión el los fallos me dice que he cambiado la línea de LuisS20 cuando solo he cambiado mi línea no entiendo.

El objetivo aquí es que entendáis cómo funciona el mecanismo de los pull requests, usado generalmente en la industria, y los diferentes apartados que lo componen. En una de las solapas, "Files", indica qué es lo que has cambiado. Si el sistema (o los mensajes de error programados) te hace alguna indicación, normalmente debes averiguar por qué es así y corregirlo. En este caso, lo que te dice es cierto, y así lo puedes comprobar en la pestaña correspondiente.

2021-09-22 10:01 UTC, JJ commented
¿Has mirado en el enlace que te he puesto?

2021-09-22 10:07 UTC, juanfran00 commented
> ¿Has mirado en el enlace que te he puesto?

Si, pero es que me voy archivos cambiados y pincho en editar archivo , cambio la línea que me corresponde y me pone que estoy cambiando la de arriba también.

2021-09-22 10:12 UTC, JJ commented
> > ¿Has mirado en el enlace que te he puesto?
> 
> Si, pero es que me voy archivos cambiados y pincho en editar archivo , cambio la línea que me corresponde y me pone que estoy cambiando la de arriba también.

Vamos a partir de la base. ¿La de arriba está cambiada? ¿Está cambiada en *este* pull request, o en la rama desde el que se ha hecho este pull request?

2021-09-22 10:14 UTC, juanfran00 commented
> > > ¿Has mirado en el enlace que te he puesto?
> > 
> > 
> > Si, pero es que me voy archivos cambiados y pincho en editar archivo, cambio la línea que me corresponde y me pone que estoy cambiando la de arriba también.
> 
> Vamos a partir de la base. ¿La de arriba está cambiada? ¿Está cambiada en _este_ pull request, o en la rama desde el que se ha hecho este pull request?

Entiendo que desde la rama en la que se ha hecho el pull resquet

2021-09-22 10:28 UTC, JJ commented
> Entiendo que desde la rama en la que se ha hecho el pull resquet

¿Qué puedes hacer entonces para que no aparezca ese cambio en la rama y por tanto en el pull request?

2021-09-22 10:40 UTC, juanfran00 commented
> > Entiendo que desde la rama en la que se ha hecho el pull resquet
> 
> ¿Qué puedes hacer entonces para que no aparezca ese cambio en la rama y por tanto en el pull request?

Supongo que con algún comando revertir el cambio

2021-09-22 10:58 UTC, JJ commented on proyectos/objetivo-0.md
> +|https://github.com/juanfran00/IV/pull/1 |0.0.2   |   |
¿De qué forma cambiar esta línea va a eliminar mágicamente el cambio que hay en la línea superior?

2021-09-22 10:59 UTC, JJ commented on proyectos/objetivo-0.md
> +| https://github.com/LuisSS20/StockAndPrices/pull/1 | 0.0.1 |  |
Aquí hay un espacio de sobra. Lo debes haber metido por equivocación. Si no lo borras, va a seguir apareciendo que hay dos líneas cambiadas.
Por favor, aprended a mirar bien las diferentes partes del PR, que son necesarias para que alcancéis los objetivos.

2021-09-22 16:12 UTC, merged